kind: Service
apiVersion: v1
metadata:
  name: registry-service
spec:
  selector:
    app: registry
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: registry-deployment
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      name: registry-pod
      labels:
        app: registry
    spec:
      containers:
        - name: registry-container
          image: registry:2
          ports:
            - containerPort: 5000
